#!/usr/bin/env python

import argparse, os, sys

from seisflows.config import config,intro, loadpy, tilde_expand, Dict
from seisflows.tools import unix


def getargs():
    parser = argparse.ArgumentParser()

    parser.add_argument('--workdir', nargs='?', 
        default=os.getcwd())

    parser.add_argument('--parameter_file', nargs='?', 
        default='parameters.py')

    parser.add_argument('--path_file', nargs='?', 
        default='paths.py')

    return parser.parse_args()


if __name__ == "__main__":
    ''' Seisflows workflow submission '''
    intro('SEISFLOWS', ' Seisflows workflow submission ')
    args = getargs()

    # register parameters
    parameters = loadpy(args.parameter_file)
    sys.modules['seisflows_parameters'] = Dict(parameters)

    # register paths
    paths = tilde_expand(loadpy(args.path_file))

    # convert relative path to absolute path
    path_dict = {}
    orig_dict = Dict(paths)

    for key in orig_dict: 
        if len(orig_dict[key]) == 0:
            path_dict[key] = ''
        else:
            path_dict[key] = os.path.abspath(orig_dict[key])
        #path = os.path.abspath(path)

    #for key in path_dict:
    #    print key + ' - ' + path_dict[key]

    #sys.modules['seisflows_paths'] = Dict(paths)
    sys.modules['seisflows_paths'] = Dict(path_dict)

    # Configure the workflow in the working directory
    unix.mkdir(args.workdir)
    unix.cd(args.workdir)

    config()

    # submit workflow
    workflow = sys.modules['seisflows_workflow']
    system = sys.modules['seisflows_system']
    system.submit(workflow)

